# Generated by Django 3.2.6 on 2022-01-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_result_std'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
