# Generated by Django 3.2.6 on 2022-01-17 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20220106_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='file',
        ),
        migrations.AddField(
            model_name='result',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
