# Generated by Django 3.2.6 on 2022-01-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20220117_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='sub',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Science', 'Science')], default='mahesh', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='medium',
            field=models.CharField(choices=[('Marathi', 'Marathi'), ('SemiEng', 'SemiEng'), ('Foundation', 'Foundation')], max_length=10),
        ),
    ]
